# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.IntegerField(default='1'),
        ),
    ]
